### ISSUE TITLE
Bug #5 feature 21: laat geen meegegeven foto's zien in het activity overzicht

### ISSUE THREAD

**Issue by happycooldude** [petersnoek/lifestyledag9#55]
Beschrijving:

Als je een activiteit aanmaakt en je geeft een foto mee maakt hij wel de activiteit aan maar laat de foto niet zien, je krijgt dan een error te zien met "kan de foto niet inladen".

Probleem:

Hij geeft een error dat hij de foto niet kan inladen

Verwacht resultaat:

Dat hij de foto laat zien die je bij het aanmaken hebt meegegeven
reproduceren:

Stappen om de bug te reproduceren

    Stap 1 maak een activiteit aan
    Stap 2 geef een foto mee
    Stap 3 maak de activiteit aan
    Stap 4 ga naar het event waar je de activiteit in hebt aangemaakt

Wie heeft de bug gevonden:
Dewi

**Comment by joshuaroovers** [comment]
bekend 'probleem'
bij het uploaden naar de live server moet je de storage:link command uitvoeren dit kan lokaal met de command: 'php artisan storage:link' of overal met de route: '/console/storagelink'
